name: Semgrep Scan

with:
  config: p/python

on:
  pull_request:
  workflow_dispatch:

jobs:
  semgrep:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep
        uses: semgrep/semgrep-action@v1
